apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arr-backup.fullname" . }}-script
  labels:
    {{- include "arr-backup.labels" . | nindent 4 }}
data:
  backup.sh: {{ .Files.Get "files/backup.sh" | quote }}
