{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arr-backup.fullname" . }}
  labels:
    {{- include "arr-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.services.radarr.enabled }}
  radarr-api-key: {{ .Values.services.radarr.apiKey | quote }}
  {{- end }}
  {{- if .Values.services.sonarr.enabled }}
  sonarr-api-key: {{ .Values.services.sonarr.apiKey | quote }}
  {{- end }}
  {{- if .Values.services.prowlarr.enabled }}
  prowlarr-api-key: {{ .Values.services.prowlarr.apiKey | quote }}
  {{- end }}
  {{- if .Values.services.bazarr.enabled }}
  bazarr-api-key: {{ .Values.services.bazarr.apiKey | quote }}
  {{- end }}
{{- end }}
