apiVersion: v2
name: jellyfin
description: A Helm chart for Kubernetes for deploying Jellyfin Media Server
type: application
version: 0.9.3
appVersion: "10.11.4"
icon: file://assets/icon.svg
keywords:
  - jellyfin
  - media
  - streaming
  - gpu
home: https://jellyfin.org
sources:
  - https://github.com/jellyfin/jellyfin
