{{- if and (not .Values.discord.existingSecret) .Values.discord.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "membarr.fullname" . }}-secret
  labels:
    {{- include "membarr.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.discord.secretKey }}: {{ .Values.discord.token | b64enc | quote }}
{{- end }}
