{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "jellyfin.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | default "Auto" | quote }}
  {{- if .Values.vpa.resourcePolicy }}
  resourcePolicy:
    {{- toYaml .Values.vpa.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end }}
