{{- range $key, $val := .Values.persistence }}
{{- if and $val.enabled (not $val.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $val.name | default (printf "%s-%s" (include "sabnzbd.fullname" $) $key) }}
  labels:
    {{- include "sabnzbd.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $val.accessMode | quote }}
  resources:
    requests:
      storage: {{ $val.size | quote }}
  {{- if $val.storageClass }}
  {{- if (eq "-" $val.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ $val.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if $val.volumeName }}
  volumeName: {{ $val.volumeName }}
  {{- end }}
{{- end }}
{{- end }}
