---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backuparr.fullname" . }}-script
  labels:
    {{- include "backuparr.labels" . | nindent 4 }}
data:
  backup.sh: |
{{ .Files.Get "files/backup.sh" | indent 4 }}
