---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "backuparr.fullname" . }}-pv
  labels:
    {{- include "backuparr.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
