{{- if .Values.openbao.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: secret
  path: infrastructure/keycloak/admin
  destination:
    name: {{ .Values.admin.existingSecretName }}
    create: true
  refreshAfter: 1h
  vaultAuthRef: {{ include "keycloak.fullname" . }}-auth
{{- end }}
