---
apiVersion: v2
name: rreading-glasses
description: Metadata service for book and audiobook management applications
type: application
version: 0.1.1
appVersion: "latest"
keywords:
  - books
  - metadata
  - readarr
  - goodreads
  - hardcover
home: https://github.com/blampe/rreading-glasses
sources:
  - https://github.com/blampe/rreading-glasses
maintainers:
  - name: geekxflood
