apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webUIPort }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: {{ .Values.service.serverPort }}
      targetPort: server
      protocol: TCP
      name: server
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
