---
apiVersion: v2
name: audiobookshelf
description: Audiobookshelf - Self-hosted audiobook and podcast server
type: application
version: 0.5.0
appVersion: "latest"
keywords:
  - audiobookshelf
  - audiobooks
  - podcasts
  - media
  - streaming
home: https://www.audiobookshelf.org/
sources:
  - https://github.com/advplyr/audiobookshelf
  - https://hub.docker.com/r/advplyr/audiobookshelf
maintainers:
  - name: geekxflood
