{{- if .Values.apiKeys.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.radarr.apiKeySecret }}
  labels:
    {{- include "playlist-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.agent.radarr.apiKeySecretKey }}: {{ .Values.apiKeys.radarrApiKey | quote }}
  {{ .Values.agent.sonarr.apiKeySecretKey }}: {{ .Values.apiKeys.sonarrApiKey | quote }}
{{- end }}
