{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rreading-glasses.fullname" . }}
  labels:
    {{- include "rreading-glasses.labels" . | nindent 4 }}
data:
  metadata-provider: {{ .Values.metadata.provider | quote }}
{{- end }}
