{{- if and .Values.enabled .Values.postgresql.internal.enabled (not .Values.postgresql.internal.auth.existingSecret) (not .Values.postgresql.external.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rreading-glasses.fullname" . }}-postgresql
  labels:
    {{- include "rreading-glasses.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.postgresql.internal.auth.password | b64enc | quote }}
{{- end }}
