apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tdarr.fullname" . }}
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tdarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tdarr.serviceAccountName" . }}
      {{- if .Values.gpu.enabled }}
      runtimeClassName: {{ .Values.gpu.runtimeClass }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- if .Values.gpu.enabled }}
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          {{- end }}
          ports:
            - name: webui
              containerPort: {{ .Values.service.webUIPort }}
              protocol: TCP
            - name: server
              containerPort: {{ .Values.service.serverPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- if .Values.gpu.enabled }}
            limits:
              nvidia.com/gpu: {{ .Values.gpu.count }}
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              nvidia.com/gpu: {{ .Values.gpu.count }}
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.server.enabled }}
            - name: server
              mountPath: /app/server
            {{- end }}
            {{- if .Values.persistence.configs.enabled }}
            - name: configs
              mountPath: /app/configs
            {{- end }}
            {{- if .Values.persistence.cache.enabled }}
            - name: cache
              mountPath: /temp
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.server.enabled }}
        - name: server
          persistentVolumeClaim:
            claimName: {{ include "tdarr.fullname" . }}-server
        {{- end }}
        {{- if .Values.persistence.configs.enabled }}
        - name: configs
          persistentVolumeClaim:
            claimName: {{ include "tdarr.fullname" . }}-configs
        {{- end }}
        {{- if .Values.persistence.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "tdarr.fullname" . }}-cache
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
