apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-config-pvc
  labels:
    {{- include "ersatztv.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-csi-iscsi-retain
