apiVersion: v1
kind: Service
metadata:
  name: {{ include "ersatztv.fullname" . }}
  labels:
    {{- include "ersatztv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.xteve.enabled }}
    - port: {{ .Values.xteve.port }}
      targetPort: xteve
      protocol: TCP
      name: xteve
    {{- end }}
  selector:
    {{- include "ersatztv.selectorLabels" . | nindent 4 }}
