{{- if and .Values.xteve.enabled .Values.xteve.persistence.enabled (not .Values.xteve.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ersatztv.fullname" . }}-xteve
  labels:
    {{- include "ersatztv.labels" . | nindent 4 }}
    app.kubernetes.io/component: xteve
spec:
  accessModes:
    - {{ .Values.xteve.persistence.accessMode }}
  {{- if .Values.xteve.persistence.storageClass }}
  storageClassName: {{ .Values.xteve.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.xteve.persistence.size }}
{{- end }}
