{{- if .Values.cfTunnel.enabled }}
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: {{ include "wizarr.fullname" . }}
  labels:
    {{- include "wizarr.labels" . | nindent 4 }}
subjects:
{{- if .Values.cfTunnel.subjects }}
  {{- range .Values.cfTunnel.subjects }}
  - kind: Service
    name: {{ .name }}
    {{- if .spec }}
    spec:
      {{- toYaml .spec | nindent 6 }}
    {{- end }}
  {{- end }}
{{- else }}
  - kind: Service
    name: {{ include "wizarr.fullname" . }}
{{- end }}
tunnelRef:
  {{- .Values.cfTunnel.tunnelRef | toYaml | nindent 2 }}
{{- end }}
