{{- if .Values.cfTunnel.enabled }}
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: {{ include "readarr.fullname" . }}
  labels:
    {{- include "readarr.labels" . | nindent 4 }}
{{- if .Values.cfTunnel.subjects }}
subjects:
  {{- range .Values.cfTunnel.subjects }}
  {{- if .name }}
  - name: {{ .name }}
    {{- if .spec }}
    {{- .spec | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- else }}
subjects:
  - name: {{ include "readarr.fullname" . }}
{{- end }}
tunnelRef:
  {{- .Values.cfTunnel.tunnelRef | toYaml | nindent 2 }}
{{- end }}
