apiVersion: v2
name: ersatztv
description: A Helm chart for ErsatzTV - custom live TV channels using your media library
type: application
version: 1.0.0
appVersion: "v25.2.0"
keywords:
  - ersatztv
  - media
  - streaming
  - iptv
  - plex
home: https://ersatztv.org
sources:
  - https://github.com/ErsatzTV/ErsatzTV
maintainers:
  - name: geekxflood
